// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWG2IVNU0KKjGJzt4A6v6_Ky4jzXYPeWc',
    appId: '1:3228866597:web:145cf2dd0fd4cff17b87cc',
    messagingSenderId: '3228866597',
    projectId: 'library-ddec8',
    authDomain: 'library-ddec8.firebaseapp.com',
    storageBucket: 'library-ddec8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0Rk43wyKPbWnownP1Vqa6Uaa7sUzi2A',
    appId: '1:3228866597:android:79e192a7b27382d97b87cc',
    messagingSenderId: '3228866597',
    projectId: 'library-ddec8',
    storageBucket: 'library-ddec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxCWN3Y6Vfkjhd_afutyWhu_DMFK-PLQ',
    appId: '1:3228866597:ios:b910a09f2ffd96647b87cc',
    messagingSenderId: '3228866597',
    projectId: 'library-ddec8',
    storageBucket: 'library-ddec8.appspot.com',
    iosBundleId: 'com.ihsanarslan.bookArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxCWN3Y6Vfkjhd_afutyWhu_DMFK-PLQ',
    appId: '1:3228866597:ios:4b7b3b8c4b1f052b7b87cc',
    messagingSenderId: '3228866597',
    projectId: 'library-ddec8',
    storageBucket: 'library-ddec8.appspot.com',
    iosBundleId: 'com.ihsanarslan.bookArchive.RunnerTests',
  );
}
